apiVersion: apps/v1
kind: Deployment
metadata:
  name: projectc-custodial-wallet
  labels:
    app: projectc-custodial-wallet
spec:
  replicas: 1
  selector:
    matchLabels:
      app: projectc-custodial-wallet
  template:
    metadata:
      labels:
        app: projectc-custodial-wallet
    spec:
      containers:
        - name: projectc-custodial-wallet
          image: REPLACE_IMAGE
          ports:
            - containerPort: 8081
