apiVersion: v1
kind: Service
metadata:
  name: projectc-custodial-wallet
  labels:
    app: projectc-custodial-wallet
spec:
  selector:
    app: projectc-custodial-wallet
  ports:
    - port: 8081
      targetPort: 8081
      protocol: TCP
      name: http
