package config

const (
	SERVICE_NAME = "projectc-custodial-wallet"

	FLAG_KEY_SERVER_HOST    = "server.host"
	FLAG_KEY_SERVER_PORT    = "server.port"
	FLAG_KEY_SERVER_VERSION = "0.1.0"
	FLAG_KEY_AUTH_USERNAME  = "auth.username"
	FLAG_KEY_AUTH_PASSWORD  = "auth.password"
	FLAG_KEY_GIN_MODE       = "gin.mode"
	FLAG_KEY_LOG_LEVEL      = "log.level"
	FLAG_KEY_MYSQL_USERNAME = "mysql.username"
	FLAG_KEY_MYSQL_PASSWORD = "mysql.password"
	FLAG_KEY_MYSQL_HOST     = "mysql.host"
	FLAG_KEY_MYSQL_PORT     = "mysql.port"
	FLAG_KEY_MYSQL_DATABASE = "mysql.database"
	FLAG_KEY_MYSQL_DSN      = "mysql.dsn"
	FLAG_KEY_MYSQL_MAX_IDLE = "mysql.maxIdleConns"
	FLAG_KEY_MYSQL_MAX_OPEN = "mysql.maxOpenConns"
	FLAG_KEY_RABBIT_URL     = "rabbitmq.url"
	FLAG_KEY_RABBIT_VHOST   = "rabbitmq.vhost"
	FLAG_KEY_RABBIT_EXCH    = "rabbitmq.exchange"
	FLAG_KEY_RABBIT_CANCEL  = "rabbitmq.cancelExchange"
	FLAG_KEY_RABBIT_TYPE    = "rabbitmq.exchangeType"
	FLAG_KEY_RABBIT_QUEUE   = "rabbitmq.queue"
	FLAG_KEY_RABBIT_ROUTING = "rabbitmq.routingKey"
	FLAG_KEY_SIGN_APP_ID    = "signature.appId"
	FLAG_KEY_SIGN_SECRET    = "signature.appSecret"
	FLAG_KEY_SIGN_SKEW      = "signature.maxSkewMillis"
	FLAG_KEY_KMS_BASE_URL   = "kms.baseUrl"
	FLAG_KEY_KMS_USERNAME   = "kms.username"
	FLAG_KEY_KMS_PASSWORD   = "kms.password"
	FLAG_KEY_CONN_BASE_URL  = "connector.baseUrl"
	FLAG_KEY_CONN_USERNAME  = "connector.username"
	FLAG_KEY_CONN_PASSWORD  = "connector.password"
	FLAG_KEY_CONN_NETWORK   = "connector.networkCode"
	FLAG_KEY_CONN_NATIVE    = "connector.nativeTokenSymbol"
	FLAG_KEY_CB_DEPOSIT     = "callback.depositUrl"
	FLAG_KEY_CB_OUT         = "callback.transferOutUrl"
	FLAG_KEY_CB_TIMEOUT     = "callback.timeoutSeconds"
	FLAG_KEY_SOL_RPC        = "solana.rpcEndpoint"
	FLAG_KEY_SOL_CU_PRICE   = "solana.computeUnitPrice"
)
